/************************************************************************************************************************************
 Module      : Ultrasonic Sensor
 Name        : ultrasonic_sensor.h
 Author      : Salma Hamdy
 Description : Header file for the ATmega32 Ultrasonic Sensor driver
 ************************************************************************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* Ultrasonic HW Ports and Pins Ids */

#define TRIGGER_PORT_ID              PORTD_ID
#define TRIGGER_PIN_ID               PIN7_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * 1. Initialize the ICU driver as required.
 * 2. Set up the ICU callback function.
 * 3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1. Send the trigger pulse by using the Ultrasonic_Trigger function.
   2. Start the measurement process via the ICU driver.
   Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * 1. This is the callback function called by the ICU driver.
   2. It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_SENSOR_H_ */
