/***********************************************************************************************************************************
 Module      : Ultrasonic Sensor
 Name        : ultrasonic_sensor.c
 Author      : Salma Hamdy
 Description : Source file for the ATmega32 Ultrasonic Sensor driver
 ***********************************************************************************************************************************/

#include "common_macros.h" /* For GET_BIT Macro */
#include "ultrasonic_sensor.h"
#include "icu.h"
#include "gpio.h"
#include <avr/io.h> /* To use the SREG register */
#include <util/delay.h>


uint8  g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_distance = 0;

/*
 * Description :
 * 1. Initialize the ICU driver as required:
 *    The ICU should be configured with a frequency of F_CPU/8 and set to detect the rising edge as the first edge.
 * 2. Set up the ICU callback function.
 *    (ICU_init and ICU_setCallBack functions should be called inside the Ultrasonic_init function.)
 * 3. Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RISING};

	/* Enable Global Interrupt I-Bit */
	SET_BIT(SREG,7);

	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Initialize the ICU driver */
	ICU_init(&ICU_Configurations);

	/* Set the direction for the trigger pin as output */
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);

}

/*
 * Description :
 * Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * 1. Send the trigger pulse by using the Ultrasonic_Trigger function.
 * 2. Start the measurement process via the ICU driver. (calculate the time it takes for the echo pulse to return)
   Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();

	/* Polling: wait until both rising and falling edges are captured then calculate the distance*/
	while(g_edgeCount != 2);

	/*
	 * Sound velocity = 340.00 m/s = 34000 cm/s
     * The distance of Object (in cm) = (340000 * Time) / 2
                                      = 17000 * Time
	 */

	/*
	 * AtMega32 Frequency = 16MHz
	 * Timer Frequency: Pre-scaler = F_CPU/8
	 * Time to execute 1 instruction is 0.5 us (So, the timer gets incremented after 0.5 us time elapse.)
     * The distance of Object (in cm) = 17000 x (TIMER value) x 5 x 10^-7 cm
                                      = 0.0085 x (TIMER value) cm
                                      = (TIMER value) / 117.6 cm
     */
	g_distance = (g_timeHigh / 117.6) + 1;

	/* Reset edge count for the next measurement */
	g_edgeCount = 0;

	return g_distance;
}

/*
 * Description :
 * 1. This is the callback function called by the ICU driver.
 * 2. It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;

	if (g_edgeCount == 1)
	{
		/*
		 * First edge (rising):
		 * Clear the timer counter register to start measurements from the first detected rising edge
		 */
	    ICU_clearTimerValue();

	    /* Detect falling edge for the coming edge*/
	    ICU_setEdgeDetectionType(FALLING);
	}
	else if (g_edgeCount == 2)
	{
		/*
		 * Second edge (falling):
		 * Store the High time value (time of echo pulse)
		 */

	    g_timeHigh = ICU_getInputCaptureValue();

	    /* Detect rising edge for the next measurement*/
	    ICU_setEdgeDetectionType(RISING);
	}
}
